### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by Mrcl1450**
WIP

### CODE REVIEW

**Comment by Laquett** [comment]
Can you get the lines of removing Oaers from VIP out of this pull request? :)

**Comment by Mrcl1450** [comment]
Done with this. Probably needs a small test first

**Comment by Mrcl1450** [comment]
@Laquett it's ready

**Comment by Mrcl1450** [comment]
@Laquett it's ready

**Comment by Mrcl1450** [comment]
Ready @Laquett

**Comment by Mrcl1450** [comment]
Bughub

**Comment by Mrcl1450** [comment]
000000000

**Comment by Mrcl1450** [comment]
@Laquett ready

**Comment by Mrcl1450** [comment]
@Laquett ready

**Pull request merged**
