### PR TITLE
Badge Preview

### PR DESCRIPTION
**Pull request by Mrcl1450**
Needs Fix

### CODE REVIEW

**Comment by Mrcl1450** [comment]
@Laquett What you think about make badges a bit bigger by default? I think it looks pretty cool.
Default it's 30px we can change it to like 45px and hover to 65px.

**Comment by Mrcl1450** [comment]
Fixed https://image.prntscr.com/image/RGQgrQMIT-GDe_qI3nAAoQ.png

**Comment by Mrcl1450** [comment]
@Laquett You can merge this for 3 in 1 *Insert sodas emote here*

**Comment by Laquett** [comment]
Closing this for now - till we can come back to it. We would need to work on getting bigger and more clear thumbnails first. :P

**Pull request closed without merging**
